# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$all'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[❯❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Alter the hostname default to remove the ssh icon
[hostname]
format = '[$hostname]($style) in '

[memory_usage]
disabled = false
threshold = -1
format = 'w/ $symbol[${ram}( | ${swap})]($style) '
